---
resources:
  - name: dowork-resources
    type: git
    source:
      uri: https://github.com/gpltaylor/concourse-test.git
      branch: master

jobs:
  - name: job-do-work
    serial: true
    plan:
      - get: dowork-resources
      - task: bump-timestamp-file
        config:
          platform: linux
          image_resource:
            type: docker-image
          run:
            path: dowork-resources/dowork.sh